[package]
name = "seedcase-propagate"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.45", features = ["serde"] }
clap = { version = "4.6.6", features = ["derive"] }
semver = { version = "1.0.28", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
serde-saphyr = "1.0.1"
serde_json = "1.0.151"
tempfile = "3.26.0"
