---
title: "Rust library interface"
---

This document describes the design of the functions forming the Rust library and
tracks the implementation status. All of these functions are external-facing
functions that are used internally in the [CLI](cli.qmd) commands.

{{< include /docs/includes/_design-status.qmd >}}

## {{< var planned >}} `read_package()`

This function reads in the data package's metadata file (currently only the
`datapackage.json` file) into a `Package` struct. While we called it `source` in
the args of many CLI commands, we call it `package` here to be clearer. "Source"
on it's own is a vague term, "source of what?", so we wanted to be explicit that
it is the data package's metadata we are reading in. Plus, the struct is called
`Package`. However, the `read_package()` has the argument called `source`, which
is the location given in the `SOURCE` arg of many of the CLI commands.

At some point we aim to support other metadata formats, but for now only
[`datapackage.json`](https://datapackage.org) is supported.

The signature is (with an internal `PackageSource` enum for the different source
locations):

```text
read_package(source: PackageSource) -> Result<Package, Error>
```

## {{< var planned >}} `read_request()`

This reads in the `request.yaml` file into the `Request` struct. This
functionality is very similar to `read_package()`. The signature is:

```text
read_request(path: &str) -> Result<Request, Error>
```

## {{< var planned >}} `check()` {#sec-check}

The `check()` function first reads and parses a `request.yaml` and a metadata
file, `datapackage.json`, checking that they contain the required keys. It then
runs the checks described below in order, returning a `CheckError` if any check
fails.

<!-- TODO: We could consider bundling up the errors and return a vector of CheckError's instead? -->

```{mermaid}
%%| label: fig-check-flow
%%| fig-cap: "The flow of input and output through the check function."
%%| fig-alt: >-
%%|   Diagram showing the flow of input and output through the `check` function.
%%|   The user provides the request and metadata file. The function completes a
%%|   set of checks, before returning a result that's either the unit type or a
%%|   CheckError.

flowchart TD
    request["request<br>path to request.yaml"]
    metadata["metadata<br>path to datapackage.json"]
    output[/"Output<br>Result&lt;(), CheckError&gt;"/]

    subgraph check ["check()"]
      read_request["read_request()<br>Parse request into a Request struct"]
      read_metadata["read_metadata()<br>Parse metadata file into a Package struct"]
      check_package_name["check_package_name()<br>Package name matches metadata"]
      check_package_version["check_package_version()<br>Package version matches metadata"]
      check_resource_names["check_resource_names()<br>Resource names match metadata"]
      check_column_names["check_column_names()<br>Column names match metadata"]
      check_row_filters["check_row_filters()<br>Row filters match metadata columns"]
    end

    request --> read_request --> check_package_name --> check_package_version --> check_resource_names --> check_column_names --> check_row_filters --> output
    metadata --> read_metadata --> check_package_name

    check:::outer_function

  classDef outer_function fill:none
```

```rs
/// Checks a request yaml against the metadata file.
///
/// The checks include:
///
/// - Required sections and keys are present in the request and metadata.
/// - Data package name and version in the request matches the metadata.
/// - The resources and columns in the request exist in the metadata.
/// - The row filters match columns in the metadata.
///
/// Errors if the request or metadata file can't be read, or if any
/// check fails.
pub fn check(request: Path, metadata: Path) -> Result<(), CheckError> {
    let request = read_request(request);
    let metadata = read_metadata(metadata);
    // Package name and version matches metadata.
    check_package_name(&request, &metadata);
    check_package_version(&request, &metadata);
    // Resource names match metadata.
    check_resource_names(&request, &metadata);
    // Column names match metadata.
    check_column_names(&request, &metadata);
    // Row filters match metadata columns (including whether the operator
    // types and values are allowed with the column type).
    check_row_filters(&request, &metadata);

    Ok(())
}
```

## {{< var planned >}} `subset_resources()`

`subset_resources()` takes the data package metadata and the request details and
applies the request to the resources into a data subset. While also visually
shown in the diagram below, briefly, it needs to:

1. Keep the selected resources.
2. Read in the resource data.
3. Filter each resource separately and keep the primary keys from matching rows.
4. Combine the primary keys of the kept rows from all resources.
5. Apply the combined primary keys as a filter to each resource separately to
   identify which rows to keep.
6. Keep only the specified columns for each resource.
7. Output the kept data as one table per kept resource, along with the
   resource's name (for later processing).

We need to filter all resources by the keys *after* the first row-filtering in
order to create the correct population for the research project.

The signature is:

```text
subset_resources(rap: CheckedRap) -> Result<Arc<[SubsettedResource]>, Errors>
```

<!-- TODO: Arc for Ids may need to be Vec -->

```{mermaid}
%%| label: fig-subset-flow
%%| fig-cap: "The flow of input and output through the `subset_resources()` function."
%%| fig-alt: >-
%%|   Diagram showing the flow of input and output through the
%%|   `subset_resources()` function. There are several steps involved, which are
%%|   textually described in the list above the diagram.

flowchart TD
    Request[/"Request"/]
    Package[/"Package"/]
    CheckedRap[/"CheckedRap"/]
    output[/"Result\< <br>Arc\< [SubsettedResource] \>,<br>Error\>"/]

    CheckedRap --> get_resource_data

    subgraph subset_resources ["subset_resources()"]
      get_resource_data["get_resource_data()"]
      RequestedResource1[/"Vec\< [RequestedResource] \><br>data as mutable reference"/]
      map_keep_requested_rows["map(keep_requested_rows)"]
      RequestedResource2[/"Arc\< [RequestedResource] \><br>row-filtered data"/]
      map_get_ids["map(get_ids)"]
      AAIds[/"Arc\< [ Arc\< [Ids] \> ] \><br>Ids as String"/]
      flatten["flatten()"]
      ArcIds[/"Arc\< [Ids] \><br>Ids as string"/]
      unique["unique()"]
      UniqueIds[/"Arc\< [Ids] \><br>No duplicate Ids"/]
      RequestedResource3[/"Arc\< [RequestedResource] \><br>original data, now with ids field"/]
      map_subset_resource["map(subset_resource)<br>Keep rows with Ids and<br>select columns"]

      get_resource_data -->
        RequestedResource1 -->
        map_keep_requested_rows -->
        RequestedResource2 -->
        map_get_ids -->
        AAIds -->
        flatten -->
        ArcIds -->
        unique -->
        UniqueIds -->|add to struct| RequestedResource3 -->
        map_subset_resource
    end

    map_subset_resource --> output

    subset_resources:::outer_function
    classDef outer_function fill:none
```
